### ISSUE TITLE
Could you please add sample use case for creating stream for notifications

### ISSUE THREAD

**Issue by careerscale** [opendaylight/docs#1]
https://github.com/opendaylight/docs/blob/master/manuals/developer-guide/src/main/asciidoc/controller/websocket-notifications.adoc

This document talks about only data change notifications. 

Could you please help with an example for generated notifications (from application)?

Thanks
Hari

**Comment by tykeal** [comment]
Please open this issue on our bug tracker at https://bugs.opendaylight.org

If you don't have an account you'll need to create on at https://identity.opendaylight.org first.
